### ISSUE TITLE
app crash

### ISSUE THREAD

**Issue by r-T3k** [yausername/dvd#51]
Used version 0.1.4
Installed app-arm64-v8a-debug.apk
App crashes when I try to set DOWNLOAD LOCATION in settings. If I search a link, select video resolution, and receive Download location prompt it will also crash if I select CHOOSE FOLDER. So because I can not assign a location, I can not download anything.

OnePlus 5t
Android v10

**Comment by xibr** [comment]
I can't reproduce the issue, it works fine on my phone Samsung Galaxy S9 plus Android 10.

**Comment by viperML** [comment]
I have the same issue on a Xiaomi with Android 12.

Here is the crash log:
<details>
<summary>Click to expand</summary>

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(Unknown Source:27)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at com.android.documentsui.ProviderExecutor.run(ProviderExecutor.java:104)
Caused by: java.lang.SecurityException: ContentService: Neither user 10062 nor current process has android.permission.CACHE_CONTENT.
	at android.os.Parcel.createExceptionOrNull(Unknown Source:7)
	at android.os.Parcel.createException(Unknown Source:0)
	at android.os.Parcel.readException(Unknown Source:11)
	at android.os.Parcel.readException(Unknown Source:10)
	at android.content.IContentService$Stub$Proxy.getCache(Unknown Source:64)
	at android.content.ContentResolver.getCache(Unknown Source:16)
	at com.android.documentsui.roots.ProvidersCache.loadRootsForAuthority(ProvidersCache.java:349)
	at com.android.documentsui.roots.ProvidersCache.getRootOneshot(ProvidersCache.java:408)
	at com.android.documentsui.roots.ProvidersCache.getRootOneshot(ProvidersCache.java:398)
	at com.android.documentsui.roots.LoadRootTask.run(LoadRootTask.java:61)
	at com.android.documentsui.roots.LoadRootTask.run(LoadRootTask.java:33)
	at com.android.documentsui.base.CheckedTask.doInBackground(CheckedTask.java:65)
	at android.os.AsyncTask$3.call(Unknown Source:20)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 1 more
Caused by: android.os.RemoteException: Remote stack trace:
	at android.app.ContextImpl.enforce(Unknown Source:97)
	at android.app.ContextImpl.enforceCallingOrSelfPermission(Unknown Source:13)
	at com.android.server.content.ContentService.getCache(Unknown Source:11)
	at android.content.IContentService$Stub.onTransact(Unknown Source:220)
	at android.os.Binder.execTransactInternal(Unknown Source:103)

```


</details>

If there is anything else I can do to debug this, let me know 👍

**Comment by viperML** [comment]
After some system updates now it works as intended 👍
